apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  type: ClusterIP
  selector:
    app: canary
    #version: "1.0"    #added as note , so it can support multiple versions.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80